"""
GitHub Gist Integration Routes
"""
from flask import Blueprint, request, jsonify
from app.middleware.auth_middleware import require_auth
from app.services.db_service import DatabaseService
import requests
import os

gist_bp = Blueprint('gist', __name__, url_prefix='/api/gist')

LANGUAGE_EXTENSIONS = {
    'python': '.py',
    'javascript': '.js',
    'typescript': '.ts',
    'java': '.java',
    'cpp': '.cpp',
    'c': '.c',
    'csharp': '.cs',
    'ruby': '.rb',
    'go': '.go',
    'php': '.php',
    'swift': '.swift',
    'kotlin': '.kt',
    'rust': '.rs'
}


@gist_bp.route('/create', methods=['POST'])
@require_auth
def create_gist(current_user):
    """Create a GitHub Gist from code."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'Request body is required'}), 400
    
    code = data.get('code', '').strip()
    language = data.get('language', 'text').lower()
    description = data.get('description', 'Generated by AI Code Generator')
    is_public = data.get('is_public', False)
    
    if not code:
        return jsonify({'error': 'Code is required'}), 400
    
    # Get user's GitHub token
    github_token = DatabaseService.get_user_github_token(current_user['id'])
    
    if not github_token:
        # Use app-level token if available
        github_token = os.getenv('GITHUB_GIST_TOKEN')
    
    if not github_token:
        return jsonify({'error': 'GitHub not connected. Please connect your GitHub account.', 'github_not_connected': True}), 400
    
    try:
        # Prepare gist data
        extension = LANGUAGE_EXTENSIONS.get(language, '.txt')
        filename = f"code{extension}"
        
        gist_data = {
            'description': description,
            'public': is_public,
            'files': {
                filename: {
                    'content': code
                }
            }
        }
        
        # Create gist via GitHub API
        headers = {
            'Authorization': f'token {github_token}',
            'Accept': 'application/vnd.github.v3+json',
            'Content-Type': 'application/json'
        }
        
        response = requests.post(
            'https://api.github.com/gists',
            json=gist_data,
            headers=headers
        )
        
        if response.status_code == 201:
            gist = response.json()
            
            # Save gist reference to database
            DatabaseService.save_gist_reference(
                user_id=current_user['id'],
                gist_id=gist['id'],
                html_url=gist['html_url'],
                description=description,
                language=language
            )
            
            return jsonify({
                'gist': {
                    'id': gist['id'],
                    'html_url': gist['html_url'],
                    'raw_url': list(gist['files'].values())[0]['raw_url'],
                    'description': gist['description'],
                    'public': gist['public']
                }
            }), 201
        else:
            error_msg = response.json().get('message', 'Failed to create gist')
            return jsonify({'error': error_msg}), response.status_code
            
    except requests.RequestException as e:
        print(f"Gist creation error: {str(e)}")
        return jsonify({'error': 'Failed to connect to GitHub'}), 503
    except Exception as e:
        print(f"Gist creation error: {str(e)}")
        return jsonify({'error': 'Failed to create gist'}), 500


@gist_bp.route('', methods=['GET'])
@require_auth
def get_user_gists(current_user):
    """Get user's created gists."""
    try:
        gists = DatabaseService.get_user_gists(current_user['id'])
        return jsonify({'gists': gists}), 200
    except Exception as e:
        print(f"Gist fetch error: {str(e)}")
        return jsonify({'error': 'Failed to fetch gists'}), 500


@gist_bp.route('/connect', methods=['POST'])
@require_auth
def connect_github(current_user):
    """Connect GitHub account by saving access token."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'Request body is required'}), 400
    
    github_token = data.get('github_token')
    
    if not github_token:
        return jsonify({'error': 'GitHub token is required'}), 400
    
    try:
        # Verify token with GitHub
        headers = {
            'Authorization': f'token {github_token}',
            'Accept': 'application/vnd.github.v3+json'
        }
        
        response = requests.get('https://api.github.com/user', headers=headers)
        
        if response.status_code != 200:
            return jsonify({'error': 'Invalid GitHub token'}), 401
        
        github_user = response.json()
        
        # Save token to database
        DatabaseService.save_github_token(
            user_id=current_user['id'],
            github_token=github_token,
            github_username=github_user.get('login')
        )
        
        return jsonify({
            'message': 'GitHub connected successfully',
            'github_user': github_user.get('login')
        }), 200
        
    except Exception as e:
        print(f"GitHub connect error: {str(e)}")
        return jsonify({'error': 'Failed to connect GitHub'}), 500


@gist_bp.route('/disconnect', methods=['POST'])
@require_auth
def disconnect_github(current_user):
    """Disconnect GitHub account."""
    try:
        DatabaseService.remove_github_token(current_user['id'])
        return jsonify({'message': 'GitHub disconnected'}), 200
    except Exception as e:
        print(f"GitHub disconnect error: {str(e)}")
        return jsonify({'error': 'Failed to disconnect GitHub'}), 500
