"""
GitHub Gist Integration Routes
"""
from flask import Blueprint, request, jsonify
from app.middleware.auth_middleware import require_auth
from app.services.db_service import DatabaseService
import requests

gist_bp = Blueprint('gist', __name__, url_prefix='/api/gist')

LANGUAGE_EXTENSIONS = {
    'python': '.py',
    'javascript': '.js',
    'typescript': '.ts',
    'java': '.java',
    'cpp': '.cpp',
    'c': '.c',
    'csharp': '.cs',
    'ruby': '.rb',
    'go': '.go',
    'php': '.php',
    'swift': '.swift',
    'kotlin': '.kt',
    'rust': '.rs'
}


@gist_bp.route('/create', methods=['POST'])
@require_auth
def create_gist(current_user):
    """Create a GitHub Gist from code."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'Request body is required'}), 400
    
    code = data.get('code', '').strip()
    language = data.get('language', 'text').lower()
    description = data.get('description', 'Generated by AI Code Generator')
    is_public = data.get('is_public', False)
    
    if not code:
        return jsonify({'error': 'Code is required'}), 400
    
    # Get user's GitHub token (user must connect their own GitHub account)
    github_token = DatabaseService.get_user_github_token(current_user['id'])
    
    if not github_token:
        return jsonify({'error': 'GitHub not connected. Please connect your GitHub account using a Personal Access Token. Note: You need to connect on each device you use.', 'github_not_connected': True}), 400
    
    try:
        # Prepare gist data
        extension = LANGUAGE_EXTENSIONS.get(language, '.txt')
        filename = f"code{extension}"
        
        gist_data = {
            'description': description,
            'public': is_public,
            'files': {
                filename: {
                    'content': code
                }
            }
        }
        
        # Create gist via GitHub API
        headers = {
            'Authorization': f'token {github_token}',
            'Accept': 'application/vnd.github.v3+json',
            'Content-Type': 'application/json'
        }
        
        response = requests.post(
            'https://api.github.com/gists',
            json=gist_data,
            headers=headers
        )
        
        if response.status_code == 201:
            gist = response.json()
            
            # Save gist reference to database
            DatabaseService.save_gist_reference(
                user_id=current_user['id'],
                gist_id=gist['id'],
                html_url=gist['html_url'],
                description=description,
                language=language
            )
            
            return jsonify({
                'gist': {
                    'id': gist['id'],
                    'html_url': gist['html_url'],
                    'raw_url': list(gist['files'].values())[0]['raw_url'],
                    'description': gist['description'],
                    'public': gist['public']
                }
            }), 201
        else:
            error_msg = response.json().get('message', 'Failed to create gist')

            # GitHub returns 401 when user's PAT is invalid/revoked.
            # Keep this as a gist-specific reconnect flow, not app logout.
            if response.status_code == 401:
                DatabaseService.remove_github_token(current_user['id'])
                return jsonify({
                    'error': 'GitHub token is invalid or expired. Please reconnect your GitHub account.',
                    'github_not_connected': True
                }), 400

            return jsonify({'error': error_msg}), response.status_code
            
    except requests.ConnectionError as e:
        print(f"Gist connection error: {str(e)}")
        return jsonify({'error': 'Failed to connect to GitHub. Please check your internet connection.'}), 503
    except requests.Timeout as e:
        print(f"Gist timeout error: {str(e)}")
        return jsonify({'error': 'GitHub request timed out. Please try again.'}), 504
    except requests.RequestException as e:
        print(f"Gist creation error: {str(e)}")
        return jsonify({'error': f'Failed to connect to GitHub: {str(e)}'}), 503
    except Exception as e:
        print(f"Gist creation error: {str(e)}")
        return jsonify({'error': 'Failed to create gist'}), 500


@gist_bp.route('', methods=['GET'])
@require_auth
def get_user_gists(current_user):
    """Get user's created gists."""
    try:
        gists = DatabaseService.get_user_gists(current_user['id'])
        return jsonify({'gists': gists}), 200
    except Exception as e:
        print(f"Gist fetch error: {str(e)}")
        return jsonify({'error': 'Failed to fetch gists'}), 500


@gist_bp.route('/connect', methods=['POST'])
@require_auth
def connect_github(current_user):
    """Connect GitHub account by saving access token."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'Request body is required'}), 400
    
    github_token = data.get('github_token')
    
    if not github_token:
        return jsonify({'error': 'GitHub token is required'}), 400
    
    try:
        # Verify token with GitHub
        headers = {
            'Authorization': f'token {github_token}',
            'Accept': 'application/vnd.github.v3+json'
        }
        
        response = requests.get('https://api.github.com/user', headers=headers)
        
        if response.status_code != 200:
            return jsonify({'error': 'Invalid GitHub token'}), 401
        
        github_user = response.json()
        
        # Save token to database
        DatabaseService.save_github_token(
            user_id=current_user['id'],
            github_token=github_token,
            github_username=github_user.get('login')
        )
        
        return jsonify({
            'message': 'GitHub connected successfully',
            'github_user': github_user.get('login')
        }), 200
        
    except Exception as e:
        print(f"GitHub connect error: {str(e)}")
        return jsonify({'error': 'Failed to connect GitHub'}), 500


@gist_bp.route('/disconnect', methods=['POST'])
@require_auth
def disconnect_github(current_user):
    """Disconnect GitHub account."""
    try:
        DatabaseService.remove_github_token(current_user['id'])
        return jsonify({'message': 'GitHub disconnected'}), 200
    except Exception as e:
        print(f"GitHub disconnect error: {str(e)}")
        return jsonify({'error': 'Failed to disconnect GitHub'}), 500


@gist_bp.route('/status', methods=['GET'])
@require_auth
def github_status(current_user):
    """Check if user has GitHub connected and return status."""
    try:
        github_token = DatabaseService.get_user_github_token(current_user['id'])
        
        if not github_token:
            return jsonify({
                'connected': False,
                'github_username': None
            }), 200
        
        # Get stored username from DB
        db = DatabaseService.get_db()
        user = db.users.find_one(
            {'_id': __import__('bson').ObjectId(current_user['id'])},
            {'github_username': 1}
        )
        github_username = user.get('github_username', '') if user else ''
        
        return jsonify({
            'connected': True,
            'github_username': github_username
        }), 200
        
    except Exception as e:
        print(f"GitHub status error: {str(e)}")
        return jsonify({'connected': False, 'github_username': None}), 200
